services:
  postgres:
    image: postgres:13
    container_name: dm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: dm_pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
  mage:
    image: mageai/mageai
    container_name: dm_mage
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6789:6789"
    environment:
      MAGE_DATA_DIR: /home/src
    volumes:
      - ./mage/state:/home/src
      - ./mage/mage_project:/home/src/mage_project
    command: >
      /bin/sh -c "mage start mage_project"

volumes:
  pgadmin_data:
